version: '3'

services:
        coredns:
                cap_add:
                        - NET_BIND_SERVICE
                cap_drop:
                        - ALL
                command: '-conf /etc/Corefile'
                image: coredns/coredns
                ports:
                        - '53:53/tcp'
                        - '53:53/udp'
                restart: always
                volumes:
                        - './Corefile:/etc/Corefile'
